<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "answer_comments".
 *
 * @property integer $id
 * @property string $smg
 * @property string $date
 * @property integer $status
 * @property integer $user_id
 * @property integer $comments_id
 *
 * @property \app\models\Comments $comments
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class AnswerComments extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'answer_comments';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['smg', 'user_id', 'comments_id'], 'required'],
            [['smg'], 'string'],
            [['date'], 'safe'],
            [['status', 'user_id', 'comments_id'], 'integer'],
            [['comments_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Comments::className(), 'targetAttribute' => ['comments_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'smg' => Yii::t('models', 'Smg'),
            'date' => Yii::t('models', 'Date'),
            'status' => Yii::t('models', 'Status'),
            'user_id' => Yii::t('models', 'User ID'),
            'comments_id' => Yii::t('models', 'Comments ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasOne(\app\models\Comments::className(), ['id' => 'comments_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




}
