<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "comments".
 *
 * @property integer $id
 * @property string $smg
 * @property string $date
 * @property integer $status
 * @property integer $user_id
 * @property integer $properties_id
 *
 * @property \app\models\AnswerComments[] $answerComments
 * @property \app\models\Properties $properties
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class Comments extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comments';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['smg', 'user_id', 'properties_id'], 'required'],
            [['smg'], 'string'],
            [['date'], 'safe'],
            [['status', 'user_id', 'properties_id'], 'integer'],
            [['properties_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Properties::className(), 'targetAttribute' => ['properties_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'smg' => Yii::t('models', 'Smg'),
            'date' => Yii::t('models', 'Date'),
            'status' => Yii::t('models', 'Status'),
            'user_id' => Yii::t('models', 'User ID'),
            'properties_id' => Yii::t('models', 'Properties ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAnswerComments()
    {
        return $this->hasMany(\app\models\AnswerComments::className(), ['comments_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProperties()
    {
        return $this->hasOne(\app\models\Properties::className(), ['id' => 'properties_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }




}
