<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "district".
 *
 * @property integer $id
 * @property string $name
 * @property integer $province_id
 *
 * @property \app\models\Province $province
 * @property \app\models\DistrictTranslate[] $districtTranslates
 * @property \app\models\PropertiesDetail[] $propertiesDetails
 * @property \app\models\Register[] $registers
 * @property string $aliasModel
 */
abstract class District extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'district';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'province_id'], 'required'],
            [['province_id'], 'integer'],
            [['name'], 'string', 'max' => 45],
            [['province_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Province::className(), 'targetAttribute' => ['province_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'province_id' => Yii::t('models', 'Province ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvince()
    {
        return $this->hasOne(\app\models\Province::className(), ['id' => 'province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrictTranslates()
    {
        return $this->hasMany(\app\models\DistrictTranslate::className(), ['district_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropertiesDetails()
    {
        return $this->hasMany(\app\models\PropertiesDetail::className(), ['district_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegisters()
    {
        return $this->hasMany(\app\models\Register::className(), ['district_id' => 'id']);
    }




}
