<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "packages".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property double $fee
 * @property integer $number
 * @property string $m_y
 *
 * @property \app\models\PackagesTranslate[] $packagesTranslates
 * @property \app\models\Properties[] $properties
 * @property string $aliasModel
 */
abstract class Packages extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'packages';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'status', 'fee', 'm_y'], 'required'],
            [['status', 'number'], 'integer'],
            [['fee'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['m_y'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'status' => Yii::t('models', 'Status'),
            'fee' => Yii::t('models', 'Fee'),
            'number' => Yii::t('models', 'Number'),
            'm_y' => Yii::t('models', 'M Y'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPackagesTranslates()
    {
        return $this->hasMany(\app\models\PackagesTranslate::className(), ['packages_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProperties()
    {
        return $this->hasMany(\app\models\Properties::className(), ['packages_id' => 'id']);
    }




}
