<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "packages_translate".
 *
 * @property integer $id
 * @property string $name
 * @property string $language
 * @property integer $packages_id
 *
 * @property \app\models\Packages $packages
 * @property string $aliasModel
 */
abstract class PackagesTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'packages_translate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'packages_id'], 'required'],
            [['packages_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['language'], 'string', 'max' => 45],
            [['packages_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Packages::className(), 'targetAttribute' => ['packages_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'language' => Yii::t('models', 'Language'),
            'packages_id' => Yii::t('models', 'Packages ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPackages()
    {
        return $this->hasOne(\app\models\Packages::className(), ['id' => 'packages_id']);
    }




}
