<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "photo".
 *
 * @property integer $id
 * @property string $name
 * @property integer $properties_detail_id
 * @property integer $main_photo
 *
 * @property \app\models\Properties $mainPhoto
 * @property \app\models\PropertiesDetail $propertiesDetail
 * @property string $aliasModel
 */
abstract class Photo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'photo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['properties_detail_id', 'main_photo'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['main_photo'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Properties::className(), 'targetAttribute' => ['main_photo' => 'id']],
            [['properties_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PropertiesDetail::className(), 'targetAttribute' => ['properties_detail_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'properties_detail_id' => Yii::t('models', 'Properties Detail ID'),
            'main_photo' => Yii::t('models', 'Main Photo'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMainPhoto()
    {
        return $this->hasOne(\app\models\Properties::className(), ['id' => 'main_photo']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropertiesDetail()
    {
        return $this->hasOne(\app\models\PropertiesDetail::className(), ['id' => 'properties_detail_id']);
    }




}
