<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "properties_detail_translate".
 *
 * @property integer $id
 * @property string $details
 * @property string $language
 * @property integer $properties_detail_id
 *
 * @property \app\models\PropertiesDetail $propertiesDetail
 * @property string $aliasModel
 */
abstract class PropertiesDetailTranslate extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'properties_detail_translate';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['details', 'properties_detail_id'], 'required'],
            [['details'], 'string'],
            [['properties_detail_id'], 'integer'],
            [['language'], 'string', 'max' => 45],
            [['properties_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PropertiesDetail::className(), 'targetAttribute' => ['properties_detail_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'details' => Yii::t('models', 'Details'),
            'language' => Yii::t('models', 'Language'),
            'properties_detail_id' => Yii::t('models', 'Properties Detail ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropertiesDetail()
    {
        return $this->hasOne(\app\models\PropertiesDetail::className(), ['id' => 'properties_detail_id']);
    }




}
