<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "properties_type".
 *
 * @property integer $id
 * @property string $name
 *
 * @property \app\models\Properties[] $properties
 * @property \app\models\PropertiesTypeTranslate[] $propertiesTypeTranslates
 * @property string $aliasModel
 */
abstract class PropertiesType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'properties_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProperties()
    {
        return $this->hasMany(\app\models\Properties::className(), ['properties_type_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPropertiesTypeTranslates()
    {
        return $this->hasMany(\app\models\PropertiesTypeTranslate::className(), ['properties_type_id' => 'id']);
    }




}
