<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "register".
 *
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property string $address
 * @property string $register_type
 *
 * @property \app\models\User[] $users
 * @property string $aliasModel
 */
abstract class Register extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const REGISTER_TYPE_LANDLORD = 'Landlord';
    const REGISTER_TYPE_TENANT = 'Tenant';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'register';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'phone', 'address', 'register_type'], 'required'],
            [['address', 'register_type'], 'string'],
            [['first_name', 'last_name'], 'string', 'max' => 255],
            [['email'], 'string', 'max' => 50],
            [['phone'], 'string', 'max' => 20],
            ['register_type', 'in', 'range' => [
                    self::REGISTER_TYPE_LANDLORD,
                    self::REGISTER_TYPE_TENANT,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'first_name' => Yii::t('models', 'First Name'),
            'last_name' => Yii::t('models', 'Last Name'),
            'email' => Yii::t('models', 'Email'),
            'phone' => Yii::t('models', 'Phone'),
            'address' => Yii::t('models', 'Address'),
            'register_type' => Yii::t('models', 'Register Type'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\app\models\User::className(), ['register_id' => 'id']);
    }




    /**
     * get column register_type enum value label
     * @param string $value
     * @return string
     */
    public static function getRegisterTypeValueLabel($value){
        $labels = self::optsRegisterType();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column register_type ENUM value labels
     * @return array
     */
    public static function optsRegisterType()
    {
        return [
            self::REGISTER_TYPE_LANDLORD => Yii::t('models', self::REGISTER_TYPE_LANDLORD),
            self::REGISTER_TYPE_TENANT => Yii::t('models', self::REGISTER_TYPE_TENANT),
        ];
    }

}
