<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $type
 * @property integer $register_id
 * @property integer $status
 * @property string $code_verify
 * @property string $payer_code
 *
 * @property \app\models\Properties[] $properties
 * @property \app\models\Register $register
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'password', 'code_verify'], 'required'],
            [['register_id', 'status'], 'integer'],
            [['payer_code'], 'string'],
            [['username', 'type'], 'string', 'max' => 255],
            [['password'], 'string', 'max' => 100],
            [['code_verify'], 'string', 'max' => 45],
            [['register_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Register::className(), 'targetAttribute' => ['register_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'username' => Yii::t('models', 'Username'),
            'password' => Yii::t('models', 'Password'),
            'type' => Yii::t('models', 'Type'),
            'register_id' => Yii::t('models', 'Register ID'),
            'status' => Yii::t('models', 'Status'),
            'code_verify' => Yii::t('models', 'Code Verify'),
            'payer_code' => Yii::t('models', 'Payer Code'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProperties()
    {
        return $this->hasMany(\app\models\Properties::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegister()
    {
        return $this->hasOne(\app\models\Register::className(), ['id' => 'register_id']);
    }




}
